jobs:
  - job: windows_powershell
    pool:
      vmImage: windows-latest
    steps:
    - pwsh: ./build.ps1 -Task Test -Bootstrap -Verbose
      displayName: Build and Test
    - task: PublishTestResults@2
      inputs:
        testRunner: NUnit
        testResultsFiles: '**/output/testResults.xml'
        testRunTitle: windows powerShell
      displayName: Publish Test Results

  - job: windows_pwsh
    pool:
      vmImage: windows-latest
    steps:
    - powershell: ./build.ps1 -Task Test -Bootstrap -Verbose
      displayName: Build and Test
    - task: PublishTestResults@2
      inputs:
        testRunner: NUnit
        testResultsFiles: '**/output/testResults.xml'
        testRunTitle: windows pwsh
      displayName: Publish Test Results

  - job: ubuntu_pwsh
    pool:
      vmImage: ubuntu-latest
    steps:
    - pwsh: ./build.ps1 -Task Test -Bootstrap -Verbose
      displayName: Build and Test
    - task: PublishTestResults@2
      inputs:
        testRunner: NUnit
        testResultsFiles: '**/output/testResults.xml'
        testRunTitle: Ubuntu
      displayName: Publish Test Results

  - job: macos_pwsh
    pool:
      vmImage: macOS-latest
    steps:
    - pwsh: ./build.ps1 -Task Test -Bootstrap -Verbose
      displayName: Build and Test
    - task: PublishTestResults@2
      inputs:
        testRunner: NUnit
        testResultsFiles: '**/output/testResults.xml'
        testRunTitle: macOS
      displayName: Publish Test Results
